"""empty message

Revision ID: 4437b06ed166
Revises: a5d451016c2d
Create Date: 2026-02-08 20:31:05.112494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4437b06ed166'
down_revision: Union[str, Sequence[str], None] = 'a5d451016c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_stocks', sa.Column('users_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'update_stocks', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'update_stocks', type_='foreignkey')
    op.drop_column('update_stocks', 'users_id')
    # ### end Alembic commands ###
