"""empty message

Revision ID: 85434aae170e
Revises: 36d15ac975e0
Create Date: 2026-02-05 21:26:49.571938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85434aae170e'
down_revision: Union[str, Sequence[str], None] = '36d15ac975e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detailedOrder', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('detailedOrder_order_id_fkey'), 'detailedOrder', type_='foreignkey')
    op.create_foreign_key(None, 'detailedOrder', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detailedOrder', type_='foreignkey')
    op.create_foreign_key(op.f('detailedOrder_order_id_fkey'), 'detailedOrder', 'orders', ['order_id'], ['id'])
    op.alter_column('detailedOrder', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
