"""empty message

Revision ID: 99b096671b1f
Revises: f95a268e2d51
Create Date: 2026-02-22 14:54:54.055786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b096671b1f'
down_revision: Union[str, Sequence[str], None] = 'f95a268e2d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('discount', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('amount_paid', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('change_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'change_amount')
    op.drop_column('orders', 'amount_paid')
    op.drop_column('orders', 'discount')
    # ### end Alembic commands ###
