"""empty message

Revision ID: a5d451016c2d
Revises: 48459ccca5c8
Create Date: 2026-02-06 21:48:21.780616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d451016c2d'
down_revision: Union[str, Sequence[str], None] = '48459ccca5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('userDetails_users_id_fkey'), 'userDetails', type_='foreignkey')
    op.create_foreign_key(None, 'userDetails', 'users', ['users_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userDetails', type_='foreignkey')
    op.create_foreign_key(op.f('userDetails_users_id_fkey'), 'userDetails', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
